version: "3.7"
services:
    pkg:
        build: .
        ports:
            - "5011:5011"
        depends_on:
            - db
    db:
        image: "mcr.microsoft.com/mssql/server"
        volumes:
          - sqlvolume:/var/opt/mssql

        environment:
            SA_PASSWORD: "Your_password123"
            ACCEPT_EULA: "Y"
        ports:
            - "1435:1433"

volumes:
  sqlvolume: