// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using lobby_service.Contexts;

namespace lobby_service.Migrations
{
    [DbContext(typeof(LobbyContext))]
    partial class LobbyContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.5")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("lobby_service.Models.Lobby", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Lobbys");
                });

            modelBuilder.Entity("lobby_service.Models.LobbyCharacter", b =>
                {
                    b.Property<int>("CharacterId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("bit");

                    b.Property<Guid?>("LobbyId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("CharacterId");

                    b.HasIndex("LobbyId");

                    b.ToTable("LobbyCharacters");
                });

            modelBuilder.Entity("lobby_service.Models.LobbyCharacter", b =>
                {
                    b.HasOne("lobby_service.Models.Lobby", null)
                        .WithMany("LobbyCharacters")
                        .HasForeignKey("LobbyId");
                });

            modelBuilder.Entity("lobby_service.Models.Lobby", b =>
                {
                    b.Navigation("LobbyCharacters");
                });
#pragma warning restore 612, 618
        }
    }
}
